# https://doc.rust-lang.org/cargo/reference/manifest.html
# https://spdx.org/licenses/

[workspace]
resolver = "3"
members = ["app/gateway", "crates/bodhi"]

[workspace.package]
edition = "2024"
rust-version = "1.92.0"

[workspace.dependencies]
