# ====================================
# gateway
# ====================================

[gateway]
url = "http://localhost:8080"
keep_alive = true

[gateway.auth]
token = ""

# ====================================
# infra
# ====================================

[infra.service]
name = "gateway"
