# ====================================
# lobby
# ====================================

[lobby]

# ====================================
# infra
# ====================================

[infra.service]
name = "lobby"
